### PR TITLE
Added hook to instrument code passed to Function() constructor.

### PR DESCRIPTION
**Pull request by JackOfMostTrades**
Although Jalangi was instrumenting dynamic code passed to eval(), it wasn't catching code passed to Function(). The new test (test47.js) should output 42 twice when run with this analysis:

this.literal = function(iid, val, hasGetterSetter) {
    if (typeof val == 'number') { val += 1; }
    return {result:val};
};

### CODE REVIEW

**Comment by esbena** [comment]
The string concatenation on line 141 in analysis.js can mask syntax errors.
Some custom syntax checks are required to preserve exception/no-exception behaviour of Jalangi.

Consider the syntactically illformed function in this program:

```javascript
var f = Function('},{');
console.log(f);
```

This patch would instrument `"(function() { },{ })"` and log the empty object, rather than complaining about a syntax error.

---
The required syntax checks:
http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.2.1 :
```
7. If P is not parsable as a FormalParameterListopt then throw a SyntaxError exception.
8. If body is not parsable as FunctionBody then throw a SyntaxError exception.
```

**Comment by JackOfMostTrades** [comment]
Good catch; it's something I hadn't considered but needs to be handled.

It seems the most "correct" thing to do would be to use the original Function() call and just instrument the body code since Acorn would throw an exception if the body is malformed (using the allowReturnOutsideFunction option when invoking acorn.parse). One challenge with this is that it doesn't add declaration callbacks for the named arguments, so additional work would need to be done to parse the parameter list and add those callbacks in.

But if the only inaccurate behavior is not throwing an exception for malformed input, perhaps the simplest thing to do would just be to construct the original uninstrumented function, allowing it to throw an exception if it would, and otherwise carry on. (So as the first line of `invokeFunctionDecl()` add `f.apply(base, args);`) Thoughts?

**Comment by esbena** [comment]
>  allowing it to throw an exception if it would, and otherwise carry on. (So as the first line of invokeFunctionDecl() add f.apply(base, args);) Thoughts?

I agree, that should be equivalent to the suggested fix in my (edited) comment.

**Comment by ksen007** [comment]
Thanks again.

**Pull request merged**
